// <auto-generated />
using System;
using Collabhost.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collabhost.Api.Migrations
{
    [DbContext(typeof(CollabhostDbContext))]
    [Migration("20260330203039_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.App", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallDirectory")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStopped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("App", (string)null);
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.AppType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AppType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456001"),
                            Description = ".NET web application hosted via Kestrel",
                            DisplayName = "ASP.NET Core",
                            ExternalId = "01JSEED00000DOTNETAPP0001",
                            IsBuiltIn = true,
                            Name = "dotnet-app"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456002"),
                            Description = "Node.js application",
                            DisplayName = "Node.js",
                            ExternalId = "01JSEED00000NODEAPP00001",
                            IsBuiltIn = true,
                            Name = "node-app"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456003"),
                            Description = "Generic executable process",
                            DisplayName = "Executable",
                            ExternalId = "01JSEED00000EXECUTABLE01",
                            IsBuiltIn = true,
                            Name = "executable"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456004"),
                            Description = "React single-page application served as static files",
                            DisplayName = "React App",
                            ExternalId = "01JSEED00000REACTAPP0001",
                            IsBuiltIn = true,
                            Name = "react-app"
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456005"),
                            Description = "Static files served directly by the reverse proxy",
                            DisplayName = "Static Site",
                            ExternalId = "01JSEED00000STATICSITE01",
                            IsBuiltIn = true,
                            Name = "static-site"
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.AppTypeCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CapabilityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityId");

                    b.HasIndex("AppTypeId", "CapabilityId")
                        .IsUnique();

                    b.ToTable("AppTypeCapability", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000001"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456001"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560001"),
                            Configuration = "{\"discoveryStrategy\":\"dotnet-runtimeconfig\",\"gracefulShutdown\":true,\"shutdownTimeoutSeconds\":30}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000002"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456001"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560002"),
                            Configuration = "{\"envVar\":\"ASPNETCORE_URLS\",\"format\":\"http://localhost:{port}\"}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000003"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456001"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560003"),
                            Configuration = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"reverseProxy\"}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000004"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456001"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560004"),
                            Configuration = "{\"endpoint\":\"/health\",\"intervalSeconds\":30,\"timeoutSeconds\":5,\"retries\":3}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000005"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456001"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560005"),
                            Configuration = "{\"defaults\":{\"ASPNETCORE_ENVIRONMENT\":\"Production\"}}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000006"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456001"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560006"),
                            Configuration = "{\"policy\":\"always\"}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000007"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456001"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560007"),
                            Configuration = "{\"enabled\":true}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000008"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456001"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560008"),
                            Configuration = "{\"targetFramework\":\"net10.0\",\"runtimeVersion\":\"10.0.x\",\"selfContained\":false}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000009"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456002"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560001"),
                            Configuration = "{\"discoveryStrategy\":\"package-json\",\"gracefulShutdown\":true,\"shutdownTimeoutSeconds\":30}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-00000000000a"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456002"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560002"),
                            Configuration = "{\"envVar\":\"PORT\",\"format\":\"{port}\"}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-00000000000b"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456002"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560003"),
                            Configuration = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"reverseProxy\"}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-00000000000c"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456002"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560004"),
                            Configuration = "{\"endpoint\":\"/health\",\"intervalSeconds\":30,\"timeoutSeconds\":5,\"retries\":3}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-00000000000d"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456002"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560006"),
                            Configuration = "{\"policy\":\"always\"}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-00000000000e"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456002"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560007"),
                            Configuration = "{\"enabled\":true}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-00000000000f"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456002"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560009"),
                            Configuration = "{\"nodeVersion\":\"22.x\",\"packageManager\":\"npm\"}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000010"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456003"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560001"),
                            Configuration = "{\"discoveryStrategy\":\"manual\",\"gracefulShutdown\":false,\"shutdownTimeoutSeconds\":10}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000011"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456003"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560002"),
                            Configuration = "{\"envVar\":\"PORT\",\"format\":\"{port}\"}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000012"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456003"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560003"),
                            Configuration = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"reverseProxy\"}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000013"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456003"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560006"),
                            Configuration = "{\"policy\":\"onCrash\"}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000014"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456003"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560007"),
                            Configuration = "{\"enabled\":false}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000015"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456004"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560003"),
                            Configuration = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"fileServer\",\"spaFallback\":true}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000016"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456004"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560009"),
                            Configuration = "{\"nodeVersion\":\"22.x\",\"packageManager\":\"npm\",\"buildCommand\":\"npm run build\"}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000017"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456004"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560010"),
                            Configuration = "{\"version\":\"18.x\",\"router\":\"react-router\",\"bundler\":\"vite\"}"
                        },
                        new
                        {
                            Id = new Guid("d0d0d0d0-aeed-4000-a000-000000000018"),
                            AppTypeId = new Guid("b1a2c3d4-e5f6-7890-abcd-ef0123456005"),
                            CapabilityId = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560003"),
                            Configuration = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"fileServer\",\"spaFallback\":false}"
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.Capability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Capability", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560001"),
                            Category = "behavioral",
                            Description = "How the app's process is discovered, started, and stopped",
                            DisplayName = "Process Management",
                            Slug = "process"
                        },
                        new
                        {
                            Id = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560002"),
                            Category = "behavioral",
                            Description = "How the platform communicates the assigned port to the app process",
                            DisplayName = "Port Injection",
                            Slug = "port-injection"
                        },
                        new
                        {
                            Id = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560003"),
                            Category = "behavioral",
                            Description = "How traffic reaches the app through the reverse proxy",
                            DisplayName = "Routing",
                            Slug = "routing"
                        },
                        new
                        {
                            Id = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560004"),
                            Category = "behavioral",
                            Description = "HTTP endpoint polled to determine app health",
                            DisplayName = "Health Check",
                            Slug = "health-check"
                        },
                        new
                        {
                            Id = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560005"),
                            Category = "behavioral",
                            Description = "Environment variables injected when the app process starts",
                            DisplayName = "Environment Variables",
                            Slug = "environment-defaults"
                        },
                        new
                        {
                            Id = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560006"),
                            Category = "behavioral",
                            Description = "How the platform responds when the app process exits unexpectedly",
                            DisplayName = "Restart Policy",
                            Slug = "restart"
                        },
                        new
                        {
                            Id = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560007"),
                            Category = "behavioral",
                            Description = "Whether the app starts automatically when Collabhost starts",
                            DisplayName = "Auto Start",
                            Slug = "auto-start"
                        },
                        new
                        {
                            Id = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560008"),
                            Category = "informational",
                            Description = ".NET runtime and framework version information",
                            DisplayName = "ASP.NET Runtime",
                            Slug = "aspnet-runtime"
                        },
                        new
                        {
                            Id = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560009"),
                            Category = "informational",
                            Description = "Node.js version and package manager information",
                            DisplayName = "Node.js Runtime",
                            Slug = "node-runtime"
                        },
                        new
                        {
                            Id = new Guid("c2b3a4d5-f6e7-8901-bcde-f01234560010"),
                            Category = "informational",
                            Description = "React framework and tooling information",
                            DisplayName = "React",
                            Slug = "react-runtime"
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.CapabilityConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppTypeCapabilityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("AppTypeCapabilityId");

                    b.HasIndex("AppId", "AppTypeCapabilityId")
                        .IsUnique();

                    b.ToTable("CapabilityConfiguration", (string)null);
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Lookups.ProcessState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.ToTable("ProcessState", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0a1c2d3-e4f5-6789-abcd-ef0123456789"),
                            DisplayName = "Stopped",
                            IsActive = true,
                            Name = "Stopped",
                            Ordinal = 0
                        },
                        new
                        {
                            Id = new Guid("c1b2a3d4-f5e6-7890-bcde-f01234567890"),
                            DisplayName = "Starting",
                            IsActive = true,
                            Name = "Starting",
                            Ordinal = 1
                        },
                        new
                        {
                            Id = new Guid("d2c3b4a5-0617-8901-cdef-012345678901"),
                            DisplayName = "Running",
                            IsActive = true,
                            Name = "Running",
                            Ordinal = 2
                        },
                        new
                        {
                            Id = new Guid("e3d4c5b6-1728-9012-def0-123456789012"),
                            DisplayName = "Stopping",
                            IsActive = true,
                            Name = "Stopping",
                            Ordinal = 3
                        },
                        new
                        {
                            Id = new Guid("f4e5d6c7-2839-0123-ef01-234567890123"),
                            DisplayName = "Crashed",
                            IsActive = true,
                            Name = "Crashed",
                            Ordinal = 4
                        },
                        new
                        {
                            Id = new Guid("05f6e7d8-394a-1234-f012-345678901234"),
                            DisplayName = "Restarting",
                            IsActive = true,
                            Name = "Restarting",
                            Ordinal = 5
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.AppTypeCapability", b =>
                {
                    b.HasOne("Collabhost.Api.Domain.Entities.AppType", null)
                        .WithMany()
                        .HasForeignKey("AppTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collabhost.Api.Domain.Entities.Capability", null)
                        .WithMany()
                        .HasForeignKey("CapabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.CapabilityConfiguration", b =>
                {
                    b.HasOne("Collabhost.Api.Domain.Entities.App", null)
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collabhost.Api.Domain.Entities.AppTypeCapability", null)
                        .WithMany()
                        .HasForeignKey("AppTypeCapabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
