// <auto-generated />
using System;
using Collabhost.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collabhost.Api.Migrations
{
    [DbContext(typeof(CollabhostDbContext))]
    [Migration("20260327190457_AddUpdateTimeoutSeconds")]
    partial class AddUpdateTimeoutSeconds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.App", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandLine")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthEndpoint")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallDirectory")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestartPolicyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateCommand")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("App", (string)null);
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.EnvironmentVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "Name")
                        .IsUnique();

                    b.ToTable("EnvironmentVariable", (string)null);
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Lookups.AppType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.ToTable("AppType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("acdb6994-2c22-42f5-bf89-68c42c9f980c"),
                            DisplayName = "Executable",
                            IsActive = true,
                            Name = "Executable",
                            Ordinal = 0
                        },
                        new
                        {
                            Id = new Guid("d71d5599-bad3-4b28-8920-1aae916bd3cb"),
                            DisplayName = "NPM Package",
                            IsActive = true,
                            Name = "NpmPackage",
                            Ordinal = 1
                        },
                        new
                        {
                            Id = new Guid("7dc8cc9f-1600-447a-85f4-cbc0fc44e6fc"),
                            DisplayName = "Static Site",
                            IsActive = true,
                            Name = "StaticSite",
                            Ordinal = 2
                        },
                        new
                        {
                            Id = new Guid("76a3e5b7-d751-4eba-aac2-b1c26c1f9ca3"),
                            DisplayName = "Proxy Service",
                            IsActive = true,
                            Name = "ProxyService",
                            Ordinal = 3
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Lookups.ProcessState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.ToTable("ProcessState", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0a1c2d3-e4f5-6789-abcd-ef0123456789"),
                            DisplayName = "Stopped",
                            IsActive = true,
                            Name = "Stopped",
                            Ordinal = 0
                        },
                        new
                        {
                            Id = new Guid("c1b2a3d4-f5e6-7890-bcde-f01234567890"),
                            DisplayName = "Starting",
                            IsActive = true,
                            Name = "Starting",
                            Ordinal = 1
                        },
                        new
                        {
                            Id = new Guid("d2c3b4a5-0617-8901-cdef-012345678901"),
                            DisplayName = "Running",
                            IsActive = true,
                            Name = "Running",
                            Ordinal = 2
                        },
                        new
                        {
                            Id = new Guid("e3d4c5b6-1728-9012-def0-123456789012"),
                            DisplayName = "Stopping",
                            IsActive = true,
                            Name = "Stopping",
                            Ordinal = 3
                        },
                        new
                        {
                            Id = new Guid("f4e5d6c7-2839-0123-ef01-234567890123"),
                            DisplayName = "Crashed",
                            IsActive = true,
                            Name = "Crashed",
                            Ordinal = 4
                        },
                        new
                        {
                            Id = new Guid("05f6e7d8-394a-1234-f012-345678901234"),
                            DisplayName = "Restarting",
                            IsActive = true,
                            Name = "Restarting",
                            Ordinal = 5
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Lookups.RestartPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.ToTable("RestartPolicy", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f2f6115-b6ef-4db4-b3c7-200a4dbb3408"),
                            DisplayName = "Never",
                            IsActive = true,
                            Name = "Never",
                            Ordinal = 0
                        },
                        new
                        {
                            Id = new Guid("a5806eba-9dcd-4145-acc3-7bcabd699829"),
                            DisplayName = "On Crash",
                            IsActive = true,
                            Name = "OnCrash",
                            Ordinal = 1
                        },
                        new
                        {
                            Id = new Guid("3902811f-674d-483a-9d6b-8b8917d83c0f"),
                            DisplayName = "Always",
                            IsActive = true,
                            Name = "Always",
                            Ordinal = 2
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.EnvironmentVariable", b =>
                {
                    b.HasOne("Collabhost.Api.Domain.Entities.App", null)
                        .WithMany("EnvironmentVariables")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.App", b =>
                {
                    b.Navigation("EnvironmentVariables");
                });
#pragma warning restore 612, 618
        }
    }
}
