// <auto-generated />
using System;
using Collabhost.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collabhost.Api.Migrations
{
    [DbContext(typeof(CollabhostDbContext))]
    partial class CollabhostDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.App", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandLine")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthEndpoint")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallDirectory")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestartPolicyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateCommand")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("App", (string)null);
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.EnvironmentVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "Name")
                        .IsUnique();

                    b.ToTable("EnvironmentVariable", (string)null);
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Lookups.AppType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.ToTable("AppType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("acdb6994-2c22-42f5-bf89-68c42c9f980c"),
                            DisplayName = "Executable",
                            IsActive = true,
                            Name = "Executable",
                            Ordinal = 0
                        },
                        new
                        {
                            Id = new Guid("d71d5599-bad3-4b28-8920-1aae916bd3cb"),
                            DisplayName = "NPM Package",
                            IsActive = true,
                            Name = "NpmPackage",
                            Ordinal = 1
                        },
                        new
                        {
                            Id = new Guid("7dc8cc9f-1600-447a-85f4-cbc0fc44e6fc"),
                            DisplayName = "Static Site",
                            IsActive = true,
                            Name = "StaticSite",
                            Ordinal = 2
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Lookups.RestartPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.ToTable("RestartPolicy", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f2f6115-b6ef-4db4-b3c7-200a4dbb3408"),
                            DisplayName = "Never",
                            IsActive = true,
                            Name = "Never",
                            Ordinal = 0
                        },
                        new
                        {
                            Id = new Guid("a5806eba-9dcd-4145-acc3-7bcabd699829"),
                            DisplayName = "On Crash",
                            IsActive = true,
                            Name = "OnCrash",
                            Ordinal = 1
                        },
                        new
                        {
                            Id = new Guid("3902811f-674d-483a-9d6b-8b8917d83c0f"),
                            DisplayName = "Always",
                            IsActive = true,
                            Name = "Always",
                            Ordinal = 2
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.EnvironmentVariable", b =>
                {
                    b.HasOne("Collabhost.Api.Domain.Entities.App", null)
                        .WithMany("EnvironmentVariables")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.App", b =>
                {
                    b.Navigation("EnvironmentVariables");
                });
#pragma warning restore 612, 618
        }
    }
}
