// <auto-generated />
using System;
using Collabhost.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collabhost.Api.Migrations
{
    [DbContext(typeof(CollabhostDbContext))]
    partial class CollabhostDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.App", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandLine")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthEndpoint")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallDirectory")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestartPolicyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateCommand")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Apps", (string)null);
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.EnvironmentVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "Name")
                        .IsUnique();

                    b.ToTable("EnvironmentVariables", (string)null);
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Lookups.AppType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.ToTable("AppTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            DisplayName = "Executable",
                            IsActive = true,
                            Name = "Executable",
                            Ordinal = 0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            DisplayName = "NPM Package",
                            IsActive = true,
                            Name = "NpmPackage",
                            Ordinal = 1
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            DisplayName = "Static Site",
                            IsActive = true,
                            Name = "StaticSite",
                            Ordinal = 2
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Lookups.RestartPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.ToTable("RestartPolicies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0002-0002-000000000001"),
                            DisplayName = "Never",
                            IsActive = true,
                            Name = "Never",
                            Ordinal = 0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0002-0002-000000000002"),
                            DisplayName = "On Crash",
                            IsActive = true,
                            Name = "OnCrash",
                            Ordinal = 1
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0002-0002-000000000003"),
                            DisplayName = "Always",
                            IsActive = true,
                            Name = "Always",
                            Ordinal = 2
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.EnvironmentVariable", b =>
                {
                    b.HasOne("Collabhost.Api.Domain.Entities.App", null)
                        .WithMany("EnvironmentVariables")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.App", b =>
                {
                    b.Navigation("EnvironmentVariables");
                });
#pragma warning restore 612, 618
        }
    }
}
