// <auto-generated />
using System;
using Collabhost.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collabhost.Api.Migrations
{
    [DbContext(typeof(CollabhostDbContext))]
    partial class CollabhostDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.App", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("App", (string)null);
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.AppType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AppType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3333aba-642e-4784-a501-856a25ae6fe5"),
                            Description = ".NET web application hosted via Kestrel",
                            DisplayName = "ASP.NET Core",
                            ExternalId = "01KN0P7JYNYACWC35R77C1KTV2",
                            IsBuiltIn = true,
                            Name = "dotnet-app"
                        },
                        new
                        {
                            Id = new Guid("49d21824-f9e6-4a44-9b12-130f8c680cb9"),
                            Description = "Node.js application",
                            DisplayName = "Node.js",
                            ExternalId = "01KN0P7JYNRBD8DC9DMKEDJX2M",
                            IsBuiltIn = true,
                            Name = "node-app"
                        },
                        new
                        {
                            Id = new Guid("bf5105c8-6a99-414c-96b6-c74aab5471f7"),
                            Description = "Generic executable process",
                            DisplayName = "Executable",
                            ExternalId = "01KN0P7JYNJRAHGC01N17NFTWW",
                            IsBuiltIn = true,
                            Name = "executable"
                        },
                        new
                        {
                            Id = new Guid("73e28a95-764f-4ae5-9c2b-a9fdea66c348"),
                            Description = "React single-page application served as static files",
                            DisplayName = "React App",
                            ExternalId = "01KN0P7JYNM6PJP07XTAXK77GR",
                            IsBuiltIn = true,
                            Name = "react-app"
                        },
                        new
                        {
                            Id = new Guid("606cdf1f-f41e-42d2-bb13-04b598de0f63"),
                            Description = "Static files served directly by the reverse proxy",
                            DisplayName = "Static Site",
                            ExternalId = "01KN0P7JYN9TDB3SPPS25Z493F",
                            IsBuiltIn = true,
                            Name = "static-site"
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.AppTypeCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CapabilityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityId");

                    b.HasIndex("AppTypeId", "CapabilityId")
                        .IsUnique();

                    b.ToTable("AppTypeCapability", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("61e355eb-1998-41ad-bfdc-069b643173c1"),
                            AppTypeId = new Guid("d3333aba-642e-4784-a501-856a25ae6fe5"),
                            CapabilityId = new Guid("8460d864-4df5-423d-bb46-c351594b6667"),
                            Configuration = "{\"discoveryStrategy\":\"dotnet-runtimeconfig\",\"gracefulShutdown\":true,\"shutdownTimeoutSeconds\":30}"
                        },
                        new
                        {
                            Id = new Guid("6d0d10bb-0764-477d-a113-b3c1f380f598"),
                            AppTypeId = new Guid("d3333aba-642e-4784-a501-856a25ae6fe5"),
                            CapabilityId = new Guid("0c66bd0a-d6b1-419d-83c2-9186d773cc52"),
                            Configuration = "{\"environmentVariableName\":\"ASPNETCORE_URLS\",\"portFormat\":\"http://localhost:{port}\"}"
                        },
                        new
                        {
                            Id = new Guid("41b486b0-037f-44e8-9a96-028c490fa48c"),
                            AppTypeId = new Guid("d3333aba-642e-4784-a501-856a25ae6fe5"),
                            CapabilityId = new Guid("6e77364e-d15c-4a02-b12d-9d8a0d623ff3"),
                            Configuration = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"reverseProxy\"}"
                        },
                        new
                        {
                            Id = new Guid("f82da976-2c10-428c-a192-6ebee06107ab"),
                            AppTypeId = new Guid("d3333aba-642e-4784-a501-856a25ae6fe5"),
                            CapabilityId = new Guid("76e18bcb-2ee9-4c9c-9d11-fb10c8f20ee0"),
                            Configuration = "{\"endpoint\":\"/health\",\"intervalSeconds\":30,\"timeoutSeconds\":5,\"retries\":3}"
                        },
                        new
                        {
                            Id = new Guid("7eb34403-7641-49aa-8a0c-7f30a39d2355"),
                            AppTypeId = new Guid("d3333aba-642e-4784-a501-856a25ae6fe5"),
                            CapabilityId = new Guid("b4fdd637-4e1f-46fb-a5fe-83bccf14a30e"),
                            Configuration = "{\"defaults\":{\"ASPNETCORE_ENVIRONMENT\":\"Production\"}}"
                        },
                        new
                        {
                            Id = new Guid("3cf3ba43-bb6a-4823-ac18-2747c57c802f"),
                            AppTypeId = new Guid("d3333aba-642e-4784-a501-856a25ae6fe5"),
                            CapabilityId = new Guid("2661f347-6af3-40a6-a0c4-57fb7e4d1f72"),
                            Configuration = "{\"policy\":\"always\"}"
                        },
                        new
                        {
                            Id = new Guid("fcd84bc2-a09c-4e1b-a1e8-2a660a0d3113"),
                            AppTypeId = new Guid("d3333aba-642e-4784-a501-856a25ae6fe5"),
                            CapabilityId = new Guid("30e21343-9124-4bec-b247-f780a5be12df"),
                            Configuration = "{\"enabled\":true}"
                        },
                        new
                        {
                            Id = new Guid("097ade9a-ab92-4a0f-ac1e-51d58e1d37cc"),
                            AppTypeId = new Guid("d3333aba-642e-4784-a501-856a25ae6fe5"),
                            CapabilityId = new Guid("1f642072-7975-4fa0-8109-4d9be5ffa909"),
                            Configuration = "{\"targetFramework\":\"net10.0\",\"runtimeVersion\":\"10.0.x\",\"selfContained\":false}"
                        },
                        new
                        {
                            Id = new Guid("f51fc05c-924b-4f6d-b0e0-8193b676a6f5"),
                            AppTypeId = new Guid("49d21824-f9e6-4a44-9b12-130f8c680cb9"),
                            CapabilityId = new Guid("8460d864-4df5-423d-bb46-c351594b6667"),
                            Configuration = "{\"discoveryStrategy\":\"package-json\",\"gracefulShutdown\":true,\"shutdownTimeoutSeconds\":30}"
                        },
                        new
                        {
                            Id = new Guid("74ff801f-58f8-4fc6-8faf-bdddecd4673e"),
                            AppTypeId = new Guid("49d21824-f9e6-4a44-9b12-130f8c680cb9"),
                            CapabilityId = new Guid("0c66bd0a-d6b1-419d-83c2-9186d773cc52"),
                            Configuration = "{\"environmentVariableName\":\"PORT\",\"portFormat\":\"{port}\"}"
                        },
                        new
                        {
                            Id = new Guid("74137008-620c-46cc-ba2c-e1e1896d25c1"),
                            AppTypeId = new Guid("49d21824-f9e6-4a44-9b12-130f8c680cb9"),
                            CapabilityId = new Guid("6e77364e-d15c-4a02-b12d-9d8a0d623ff3"),
                            Configuration = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"reverseProxy\"}"
                        },
                        new
                        {
                            Id = new Guid("a5792083-b9e7-4ef7-8f3f-b9835d908362"),
                            AppTypeId = new Guid("49d21824-f9e6-4a44-9b12-130f8c680cb9"),
                            CapabilityId = new Guid("76e18bcb-2ee9-4c9c-9d11-fb10c8f20ee0"),
                            Configuration = "{\"endpoint\":\"/health\",\"intervalSeconds\":30,\"timeoutSeconds\":5,\"retries\":3}"
                        },
                        new
                        {
                            Id = new Guid("088e99f8-dd64-4d14-bed2-e0e2027ac1b4"),
                            AppTypeId = new Guid("49d21824-f9e6-4a44-9b12-130f8c680cb9"),
                            CapabilityId = new Guid("2661f347-6af3-40a6-a0c4-57fb7e4d1f72"),
                            Configuration = "{\"policy\":\"always\"}"
                        },
                        new
                        {
                            Id = new Guid("909f7e6d-451c-4bff-b8d5-bfb04f3b5116"),
                            AppTypeId = new Guid("49d21824-f9e6-4a44-9b12-130f8c680cb9"),
                            CapabilityId = new Guid("30e21343-9124-4bec-b247-f780a5be12df"),
                            Configuration = "{\"enabled\":true}"
                        },
                        new
                        {
                            Id = new Guid("84810cdc-4299-42f1-903d-8fff82ed4e92"),
                            AppTypeId = new Guid("49d21824-f9e6-4a44-9b12-130f8c680cb9"),
                            CapabilityId = new Guid("0ba21247-bf12-4487-b2ad-e4c84a784d75"),
                            Configuration = "{\"nodeVersion\":\"22.x\",\"packageManager\":\"npm\"}"
                        },
                        new
                        {
                            Id = new Guid("ecb72690-91c9-43ae-9039-92ada963271c"),
                            AppTypeId = new Guid("bf5105c8-6a99-414c-96b6-c74aab5471f7"),
                            CapabilityId = new Guid("8460d864-4df5-423d-bb46-c351594b6667"),
                            Configuration = "{\"discoveryStrategy\":\"manual\",\"gracefulShutdown\":false,\"shutdownTimeoutSeconds\":10}"
                        },
                        new
                        {
                            Id = new Guid("254d4414-246f-44e5-82d0-0075b3f994c0"),
                            AppTypeId = new Guid("bf5105c8-6a99-414c-96b6-c74aab5471f7"),
                            CapabilityId = new Guid("0c66bd0a-d6b1-419d-83c2-9186d773cc52"),
                            Configuration = "{\"environmentVariableName\":\"PORT\",\"portFormat\":\"{port}\"}"
                        },
                        new
                        {
                            Id = new Guid("fa660eb9-810a-47c1-8010-799481c4dca5"),
                            AppTypeId = new Guid("bf5105c8-6a99-414c-96b6-c74aab5471f7"),
                            CapabilityId = new Guid("6e77364e-d15c-4a02-b12d-9d8a0d623ff3"),
                            Configuration = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"reverseProxy\"}"
                        },
                        new
                        {
                            Id = new Guid("14cb559d-7675-43bb-acdd-f1f15671c570"),
                            AppTypeId = new Guid("bf5105c8-6a99-414c-96b6-c74aab5471f7"),
                            CapabilityId = new Guid("2661f347-6af3-40a6-a0c4-57fb7e4d1f72"),
                            Configuration = "{\"policy\":\"onCrash\"}"
                        },
                        new
                        {
                            Id = new Guid("408ae72c-0771-4817-a5ed-950419ee5771"),
                            AppTypeId = new Guid("bf5105c8-6a99-414c-96b6-c74aab5471f7"),
                            CapabilityId = new Guid("30e21343-9124-4bec-b247-f780a5be12df"),
                            Configuration = "{\"enabled\":false}"
                        },
                        new
                        {
                            Id = new Guid("e708632b-d307-4045-9778-679d979b1578"),
                            AppTypeId = new Guid("73e28a95-764f-4ae5-9c2b-a9fdea66c348"),
                            CapabilityId = new Guid("6e77364e-d15c-4a02-b12d-9d8a0d623ff3"),
                            Configuration = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"fileServer\",\"spaFallback\":true}"
                        },
                        new
                        {
                            Id = new Guid("d9c3ac3e-052c-4992-ac36-bd3079499663"),
                            AppTypeId = new Guid("73e28a95-764f-4ae5-9c2b-a9fdea66c348"),
                            CapabilityId = new Guid("0ba21247-bf12-4487-b2ad-e4c84a784d75"),
                            Configuration = "{\"nodeVersion\":\"22.x\",\"packageManager\":\"npm\",\"buildCommand\":\"npm run build\"}"
                        },
                        new
                        {
                            Id = new Guid("b256a4b1-86fe-46db-ab50-0061e7854996"),
                            AppTypeId = new Guid("73e28a95-764f-4ae5-9c2b-a9fdea66c348"),
                            CapabilityId = new Guid("2bc51a48-5e56-4c27-958a-615009fea233"),
                            Configuration = "{\"version\":\"18.x\",\"router\":\"react-router\",\"bundler\":\"vite\"}"
                        },
                        new
                        {
                            Id = new Guid("a4cbac96-a44d-4823-9924-e4a530ee96b2"),
                            AppTypeId = new Guid("606cdf1f-f41e-42d2-bb13-04b598de0f63"),
                            CapabilityId = new Guid("6e77364e-d15c-4a02-b12d-9d8a0d623ff3"),
                            Configuration = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"fileServer\",\"spaFallback\":false}"
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.Capability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Capability", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8460d864-4df5-423d-bb46-c351594b6667"),
                            Category = "behavioral",
                            Description = "How the app's process is discovered, started, and stopped",
                            DisplayName = "Process Management",
                            Slug = "process"
                        },
                        new
                        {
                            Id = new Guid("0c66bd0a-d6b1-419d-83c2-9186d773cc52"),
                            Category = "behavioral",
                            Description = "How the platform communicates the assigned port to the app process",
                            DisplayName = "Port Injection",
                            Slug = "port-injection"
                        },
                        new
                        {
                            Id = new Guid("6e77364e-d15c-4a02-b12d-9d8a0d623ff3"),
                            Category = "behavioral",
                            Description = "How traffic reaches the app through the reverse proxy",
                            DisplayName = "Routing",
                            Slug = "routing"
                        },
                        new
                        {
                            Id = new Guid("76e18bcb-2ee9-4c9c-9d11-fb10c8f20ee0"),
                            Category = "behavioral",
                            Description = "HTTP endpoint polled to determine app health",
                            DisplayName = "Health Check",
                            Slug = "health-check"
                        },
                        new
                        {
                            Id = new Guid("b4fdd637-4e1f-46fb-a5fe-83bccf14a30e"),
                            Category = "behavioral",
                            Description = "Environment variables injected when the app process starts",
                            DisplayName = "Environment Variables",
                            Slug = "environment-defaults"
                        },
                        new
                        {
                            Id = new Guid("2661f347-6af3-40a6-a0c4-57fb7e4d1f72"),
                            Category = "behavioral",
                            Description = "How the platform responds when the app process exits unexpectedly",
                            DisplayName = "Restart Policy",
                            Slug = "restart"
                        },
                        new
                        {
                            Id = new Guid("30e21343-9124-4bec-b247-f780a5be12df"),
                            Category = "behavioral",
                            Description = "Whether the app starts automatically when Collabhost starts",
                            DisplayName = "Auto Start",
                            Slug = "auto-start"
                        },
                        new
                        {
                            Id = new Guid("1f642072-7975-4fa0-8109-4d9be5ffa909"),
                            Category = "informational",
                            Description = ".NET runtime and framework version information",
                            DisplayName = "ASP.NET Runtime",
                            Slug = "aspnet-runtime"
                        },
                        new
                        {
                            Id = new Guid("0ba21247-bf12-4487-b2ad-e4c84a784d75"),
                            Category = "informational",
                            Description = "Node.js version and package manager information",
                            DisplayName = "Node.js Runtime",
                            Slug = "node-runtime"
                        },
                        new
                        {
                            Id = new Guid("2bc51a48-5e56-4c27-958a-615009fea233"),
                            Category = "informational",
                            Description = "React framework and tooling information",
                            DisplayName = "React",
                            Slug = "react-runtime"
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.CapabilityConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppTypeCapabilityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("AppTypeCapabilityId");

                    b.HasIndex("AppId", "AppTypeCapabilityId")
                        .IsUnique();

                    b.ToTable("CapabilityConfiguration", (string)null);
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Lookups.ProcessState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.ToTable("ProcessState", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d413f4ed-d764-4277-ab4c-190822d22789"),
                            DisplayName = "Stopped",
                            IsActive = true,
                            Name = "Stopped",
                            Ordinal = 0
                        },
                        new
                        {
                            Id = new Guid("b9057b8a-7fe7-407c-84e2-dcdc41caeee1"),
                            DisplayName = "Starting",
                            IsActive = true,
                            Name = "Starting",
                            Ordinal = 1
                        },
                        new
                        {
                            Id = new Guid("2cd5e4ed-ac0e-40eb-abad-3b56819f97a4"),
                            DisplayName = "Running",
                            IsActive = true,
                            Name = "Running",
                            Ordinal = 2
                        },
                        new
                        {
                            Id = new Guid("0d98c241-6630-4f0f-a16e-bad8a013eb31"),
                            DisplayName = "Stopping",
                            IsActive = true,
                            Name = "Stopping",
                            Ordinal = 3
                        },
                        new
                        {
                            Id = new Guid("55331f23-8eae-4e56-811d-8bbdeaca03ca"),
                            DisplayName = "Crashed",
                            IsActive = true,
                            Name = "Crashed",
                            Ordinal = 4
                        },
                        new
                        {
                            Id = new Guid("517b2fb1-e5f9-4fdd-98de-10cedec5bcc3"),
                            DisplayName = "Restarting",
                            IsActive = true,
                            Name = "Restarting",
                            Ordinal = 5
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.AppTypeCapability", b =>
                {
                    b.HasOne("Collabhost.Api.Domain.Entities.AppType", null)
                        .WithMany()
                        .HasForeignKey("AppTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collabhost.Api.Domain.Entities.Capability", null)
                        .WithMany()
                        .HasForeignKey("CapabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Collabhost.Api.Domain.Entities.CapabilityConfiguration", b =>
                {
                    b.HasOne("Collabhost.Api.Domain.Entities.App", null)
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collabhost.Api.Domain.Entities.AppTypeCapability", null)
                        .WithMany()
                        .HasForeignKey("AppTypeCapabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
