// <auto-generated />
using System;
using Collabhost.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collabhost.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403010612_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Collabhost.Api.Capabilities.CapabilityBinding", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppTypeId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitySlug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppTypeId", "CapabilitySlug")
                        .IsUnique();

                    b.ToTable("CapabilityBindings");

                    b.HasData(
                        new
                        {
                            Id = "01JQDZ00000000000DNETBND01",
                            AppTypeId = "01JQDZ000000000000000DNETA",
                            CapabilitySlug = "artifact",
                            DefaultConfigurationJson = "{\"location\":\"\"}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000DNETBND02",
                            AppTypeId = "01JQDZ000000000000000DNETA",
                            CapabilitySlug = "process",
                            DefaultConfigurationJson = "{\"discoveryStrategy\":\"DotNetRuntimeConfiguration\",\"gracefulShutdown\":true,\"shutdownTimeoutSeconds\":30}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000DNETBND03",
                            AppTypeId = "01JQDZ000000000000000DNETA",
                            CapabilitySlug = "port-injection",
                            DefaultConfigurationJson = "{\"environmentVariableName\":\"ASPNETCORE_URLS\",\"portFormat\":\"http://localhost:{port}\"}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000DNETBND04",
                            AppTypeId = "01JQDZ000000000000000DNETA",
                            CapabilitySlug = "routing",
                            DefaultConfigurationJson = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"ReverseProxy\",\"spaFallback\":false}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000DNETBND05",
                            AppTypeId = "01JQDZ000000000000000DNETA",
                            CapabilitySlug = "health-check",
                            DefaultConfigurationJson = "{\"endpoint\":\"/health\",\"intervalSeconds\":30,\"timeoutSeconds\":5}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000DNETBND06",
                            AppTypeId = "01JQDZ000000000000000DNETA",
                            CapabilitySlug = "restart",
                            DefaultConfigurationJson = "{\"policy\":\"OnCrash\"}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000DNETBND07",
                            AppTypeId = "01JQDZ000000000000000DNETA",
                            CapabilitySlug = "auto-start",
                            DefaultConfigurationJson = "{\"enabled\":true}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000DNETBND08",
                            AppTypeId = "01JQDZ000000000000000DNETA",
                            CapabilitySlug = "environment-defaults",
                            DefaultConfigurationJson = "{\"variables\":{\"ASPNETCORE_ENVIRONMENT\":\"Production\"}}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000NZDEBND01",
                            AppTypeId = "01JQDZ000000000000000QZDEA",
                            CapabilitySlug = "artifact",
                            DefaultConfigurationJson = "{\"location\":\"\"}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000NZDEBND02",
                            AppTypeId = "01JQDZ000000000000000QZDEA",
                            CapabilitySlug = "process",
                            DefaultConfigurationJson = "{\"discoveryStrategy\":\"PackageJson\",\"gracefulShutdown\":true,\"shutdownTimeoutSeconds\":15}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000NZDEBND03",
                            AppTypeId = "01JQDZ000000000000000QZDEA",
                            CapabilitySlug = "port-injection",
                            DefaultConfigurationJson = "{\"environmentVariableName\":\"PORT\",\"portFormat\":\"{port}\"}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000NZDEBND04",
                            AppTypeId = "01JQDZ000000000000000QZDEA",
                            CapabilitySlug = "routing",
                            DefaultConfigurationJson = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"ReverseProxy\",\"spaFallback\":false}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000NZDEBND05",
                            AppTypeId = "01JQDZ000000000000000QZDEA",
                            CapabilitySlug = "health-check",
                            DefaultConfigurationJson = "{\"endpoint\":\"/health\",\"intervalSeconds\":30,\"timeoutSeconds\":5}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000NZDEBND06",
                            AppTypeId = "01JQDZ000000000000000QZDEA",
                            CapabilitySlug = "restart",
                            DefaultConfigurationJson = "{\"policy\":\"OnCrash\"}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000NZDEBND07",
                            AppTypeId = "01JQDZ000000000000000QZDEA",
                            CapabilitySlug = "auto-start",
                            DefaultConfigurationJson = "{\"enabled\":true}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000NZDEBND08",
                            AppTypeId = "01JQDZ000000000000000QZDEA",
                            CapabilitySlug = "environment-defaults",
                            DefaultConfigurationJson = "{\"variables\":{\"NODE_ENV\":\"production\"}}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000STATBND01",
                            AppTypeId = "01JQDZ000000000000000STATA",
                            CapabilitySlug = "artifact",
                            DefaultConfigurationJson = "{\"location\":\"\"}"
                        },
                        new
                        {
                            Id = "01JQDZ00000000000STATBND02",
                            AppTypeId = "01JQDZ000000000000000STATA",
                            CapabilitySlug = "routing",
                            DefaultConfigurationJson = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"FileServer\",\"spaFallback\":true}"
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Capabilities.CapabilityOverride", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitySlug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "CapabilitySlug")
                        .IsUnique();

                    b.ToTable("CapabilityOverrides");
                });

            modelBuilder.Entity("Collabhost.Api.Registry.App", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppTypeId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppTypeId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("Collabhost.Api.Registry.AppType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("AppTypes");

                    b.HasData(
                        new
                        {
                            Id = "01JQDZ000000000000000DNETA",
                            CreatedAt = new DateTime(2026, 4, 3, 1, 6, 12, 198, DateTimeKind.Utc).AddTicks(6729),
                            Description = "ASP.NET Core or .NET console application",
                            DisplayName = ".NET Application",
                            IsBuiltIn = true,
                            MetadataJson = "{\"runtime\":{\"name\":\".NET\",\"version\":\"10\",\"targetFramework\":\"net10.0\"}}",
                            Slug = "dotnet-app"
                        },
                        new
                        {
                            Id = "01JQDZ000000000000000QZDEA",
                            CreatedAt = new DateTime(2026, 4, 3, 1, 6, 12, 199, DateTimeKind.Utc).AddTicks(3222),
                            Description = "Server-side JavaScript with npm",
                            DisplayName = "Node.js Application",
                            IsBuiltIn = true,
                            MetadataJson = "{\"runtime\":{\"name\":\"Node.js\",\"version\":\"22\",\"packageManager\":\"npm\"}}",
                            Slug = "nodejs-app"
                        },
                        new
                        {
                            Id = "01JQDZ000000000000000STATA",
                            CreatedAt = new DateTime(2026, 4, 3, 1, 6, 12, 199, DateTimeKind.Utc).AddTicks(3229),
                            Description = "Static files served by Caddy",
                            DisplayName = "Static Site",
                            IsBuiltIn = true,
                            Slug = "static-site"
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Capabilities.CapabilityBinding", b =>
                {
                    b.HasOne("Collabhost.Api.Registry.AppType", null)
                        .WithMany("Bindings")
                        .HasForeignKey("AppTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collabhost.Api.Capabilities.CapabilityOverride", b =>
                {
                    b.HasOne("Collabhost.Api.Registry.App", null)
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collabhost.Api.Registry.App", b =>
                {
                    b.HasOne("Collabhost.Api.Registry.AppType", "AppType")
                        .WithMany()
                        .HasForeignKey("AppTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppType");
                });

            modelBuilder.Entity("Collabhost.Api.Registry.AppType", b =>
                {
                    b.Navigation("Bindings");
                });
#pragma warning restore 612, 618
        }
    }
}
