// <auto-generated />
using System;
using Collabhost.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collabhost.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Collabhost.Api.Capabilities.CapabilityBinding", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppTypeId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitySlug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppTypeId", "CapabilitySlug")
                        .IsUnique();

                    b.ToTable("CapabilityBindings");

                    b.HasData(
                        new
                        {
                            Id = "01KN8K1MRTP60DVWP6ERZ8R4F9",
                            AppTypeId = "01KN8K1MRQ0K06ADYJJ8VAXG5Y",
                            CapabilitySlug = "artifact",
                            DefaultConfigurationJson = "{\"location\":\"\"}"
                        },
                        new
                        {
                            Id = "01KN8K1MRTJD1NCG0J9R4364MJ",
                            AppTypeId = "01KN8K1MRQ0K06ADYJJ8VAXG5Y",
                            CapabilitySlug = "process",
                            DefaultConfigurationJson = "{\"discoveryStrategy\":\"DotNetRuntimeConfiguration\",\"gracefulShutdown\":true,\"shutdownTimeoutSeconds\":30}"
                        },
                        new
                        {
                            Id = "01KN8K1MRTCFS85XS4TRW6EGSR",
                            AppTypeId = "01KN8K1MRQ0K06ADYJJ8VAXG5Y",
                            CapabilitySlug = "port-injection",
                            DefaultConfigurationJson = "{\"environmentVariableName\":\"ASPNETCORE_URLS\",\"portFormat\":\"http://localhost:{port}\"}"
                        },
                        new
                        {
                            Id = "01KN8K1MRT34CN63B8QZ96N3Q7",
                            AppTypeId = "01KN8K1MRQ0K06ADYJJ8VAXG5Y",
                            CapabilitySlug = "routing",
                            DefaultConfigurationJson = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"ReverseProxy\",\"spaFallback\":false}"
                        },
                        new
                        {
                            Id = "01KN8K1MRTG49PHRKY1N3DMFKN",
                            AppTypeId = "01KN8K1MRQ0K06ADYJJ8VAXG5Y",
                            CapabilitySlug = "health-check",
                            DefaultConfigurationJson = "{\"endpoint\":\"/health\",\"intervalSeconds\":30,\"timeoutSeconds\":5}"
                        },
                        new
                        {
                            Id = "01KN8K1MRTGF8GQ3X2CFS2JCQS",
                            AppTypeId = "01KN8K1MRQ0K06ADYJJ8VAXG5Y",
                            CapabilitySlug = "restart",
                            DefaultConfigurationJson = "{\"policy\":\"OnCrash\"}"
                        },
                        new
                        {
                            Id = "01KN8K1MRT1SW33ZS6DK4TTGKB",
                            AppTypeId = "01KN8K1MRQ0K06ADYJJ8VAXG5Y",
                            CapabilitySlug = "auto-start",
                            DefaultConfigurationJson = "{\"enabled\":true}"
                        },
                        new
                        {
                            Id = "01KN8K1MRT0B5TF2TTXV68DAFJ",
                            AppTypeId = "01KN8K1MRQ0K06ADYJJ8VAXG5Y",
                            CapabilitySlug = "environment-defaults",
                            DefaultConfigurationJson = "{\"variables\":{\"ASPNETCORE_ENVIRONMENT\":\"Production\"}}"
                        },
                        new
                        {
                            Id = "01KN8K1MRTHFBR5P75WEE5K3NT",
                            AppTypeId = "01KN8K1MRT4XGXXW5BBQ8YZNN2",
                            CapabilitySlug = "artifact",
                            DefaultConfigurationJson = "{\"location\":\"\"}"
                        },
                        new
                        {
                            Id = "01KN8K1MRT9RES6FCWSNFYNXGK",
                            AppTypeId = "01KN8K1MRT4XGXXW5BBQ8YZNN2",
                            CapabilitySlug = "process",
                            DefaultConfigurationJson = "{\"discoveryStrategy\":\"PackageJson\",\"gracefulShutdown\":true,\"shutdownTimeoutSeconds\":15}"
                        },
                        new
                        {
                            Id = "01KN8K1MRTD4TJKKDPGHG36Z4K",
                            AppTypeId = "01KN8K1MRT4XGXXW5BBQ8YZNN2",
                            CapabilitySlug = "port-injection",
                            DefaultConfigurationJson = "{\"environmentVariableName\":\"PORT\",\"portFormat\":\"{port}\"}"
                        },
                        new
                        {
                            Id = "01KN8K1MRTGPRVSG3F6EJBB8CM",
                            AppTypeId = "01KN8K1MRT4XGXXW5BBQ8YZNN2",
                            CapabilitySlug = "routing",
                            DefaultConfigurationJson = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"ReverseProxy\",\"spaFallback\":false}"
                        },
                        new
                        {
                            Id = "01KN8K1MRTEFCM6C0ZXM6GFM68",
                            AppTypeId = "01KN8K1MRT4XGXXW5BBQ8YZNN2",
                            CapabilitySlug = "health-check",
                            DefaultConfigurationJson = "{\"endpoint\":\"/health\",\"intervalSeconds\":30,\"timeoutSeconds\":5}"
                        },
                        new
                        {
                            Id = "01KN8K1MRT9D970Y0XZR74W1Z1",
                            AppTypeId = "01KN8K1MRT4XGXXW5BBQ8YZNN2",
                            CapabilitySlug = "restart",
                            DefaultConfigurationJson = "{\"policy\":\"OnCrash\"}"
                        },
                        new
                        {
                            Id = "01KN8K1MRTT086R433KGMBT21A",
                            AppTypeId = "01KN8K1MRT4XGXXW5BBQ8YZNN2",
                            CapabilitySlug = "auto-start",
                            DefaultConfigurationJson = "{\"enabled\":true}"
                        },
                        new
                        {
                            Id = "01KN8K1MRTZZ9PJ1QMZSG5QHRE",
                            AppTypeId = "01KN8K1MRT4XGXXW5BBQ8YZNN2",
                            CapabilitySlug = "environment-defaults",
                            DefaultConfigurationJson = "{\"variables\":{\"NODE_ENV\":\"production\"}}"
                        },
                        new
                        {
                            Id = "01KN8K1MRTE14RGEAS4VDD44P3",
                            AppTypeId = "01KN8K1MRT26VCX65J1ZSVWESB",
                            CapabilitySlug = "artifact",
                            DefaultConfigurationJson = "{\"location\":\"\"}"
                        },
                        new
                        {
                            Id = "01KN8K1MRTETFY88Z8FTJGCBB5",
                            AppTypeId = "01KN8K1MRT26VCX65J1ZSVWESB",
                            CapabilitySlug = "routing",
                            DefaultConfigurationJson = "{\"domainPattern\":\"{slug}.collab.internal\",\"serveMode\":\"FileServer\",\"spaFallback\":true}"
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Capabilities.CapabilityOverride", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitySlug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "CapabilitySlug")
                        .IsUnique();

                    b.ToTable("CapabilityOverrides");
                });

            modelBuilder.Entity("Collabhost.Api.Registry.App", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppTypeId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppTypeId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("Collabhost.Api.Registry.AppType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("AppTypes");

                    b.HasData(
                        new
                        {
                            Id = "01KN8K1MRQ0K06ADYJJ8VAXG5Y",
                            CreatedAt = new DateTime(2026, 4, 3, 2, 37, 13, 803, DateTimeKind.Utc).AddTicks(5489),
                            Description = "ASP.NET Core or .NET console application",
                            DisplayName = ".NET Application",
                            IsBuiltIn = true,
                            MetadataJson = "{\"runtime\":{\"name\":\".NET\",\"version\":\"10\",\"targetFramework\":\"net10.0\"}}",
                            Slug = "dotnet-app"
                        },
                        new
                        {
                            Id = "01KN8K1MRT4XGXXW5BBQ8YZNN2",
                            CreatedAt = new DateTime(2026, 4, 3, 2, 37, 13, 804, DateTimeKind.Utc).AddTicks(2115),
                            Description = "Server-side JavaScript with npm",
                            DisplayName = "Node.js Application",
                            IsBuiltIn = true,
                            MetadataJson = "{\"runtime\":{\"name\":\"Node.js\",\"version\":\"22\",\"packageManager\":\"npm\"}}",
                            Slug = "nodejs-app"
                        },
                        new
                        {
                            Id = "01KN8K1MRT26VCX65J1ZSVWESB",
                            CreatedAt = new DateTime(2026, 4, 3, 2, 37, 13, 804, DateTimeKind.Utc).AddTicks(2127),
                            Description = "Static files served by Caddy",
                            DisplayName = "Static Site",
                            IsBuiltIn = true,
                            Slug = "static-site"
                        });
                });

            modelBuilder.Entity("Collabhost.Api.Capabilities.CapabilityBinding", b =>
                {
                    b.HasOne("Collabhost.Api.Registry.AppType", null)
                        .WithMany("Bindings")
                        .HasForeignKey("AppTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collabhost.Api.Capabilities.CapabilityOverride", b =>
                {
                    b.HasOne("Collabhost.Api.Registry.App", null)
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collabhost.Api.Registry.App", b =>
                {
                    b.HasOne("Collabhost.Api.Registry.AppType", "AppType")
                        .WithMany()
                        .HasForeignKey("AppTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppType");
                });

            modelBuilder.Entity("Collabhost.Api.Registry.AppType", b =>
                {
                    b.Navigation("Bindings");
                });
#pragma warning restore 612, 618
        }
    }
}
